name: Run MATLAB Script on GitHub-Hosted Runner
# on: [push]
# cron: 
# * * * * * 
# | | | | |
# | | | | |- weekday (0:sun 6: sat)
# | | | |--- month
# | | |----- day
# | |------- hour
# |--------- minute
# This job runs every 10 minutes
on:
    schedule:
    # On weekdays: In KST, 8AM & 10AM to midnight (skipping 9AM KST due to many request in 0'o clock at UTC)
      - cron: '0 23,0-15 * * 1-5'
    # On weekends: In KST, 8AM to midnight with 2 hours step.
      - cron: '0 23,1,3,5,7,9,11,13,15 * * 0,6'
jobs:
  my-job:
    name: Create tag pages for blog postings
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: merge_RSS
